### ISSUE TITLE
Raging bull not the correct type

### ISSUE THREAD

**Issue by MoltenGluten** [doshidak/showdex#129]
When facing a corvinight with my blaze breed tauros, raging bull was shown to do 1/3 of the damage of close combat

**Comment by doshidak** [comment]
Hmm, that might be a bug with the underlying calculator. (If it is, there are ways to fix this on our end, luckily.) I'll look into this.

Thanks for the report!

**Comment by doshidak** [comment]
Found the issue!

Was caused by Showdown internally renaming the different formes of *Tauros-Paldea*, specifically *Tauros-Paldea-**Fire*** becoming *Tauros-Paldea-**Blaze*** & *Tauros-Paldea-**Water*** becoming *Tauros-Paldea-**Aqua***.

The underlying calculator ([`@smogon/calc`](https://github.com/smogon/damage-calc/tree/master/calc)) in v1.1.4 is outdated, still referring to the original forme names when determining whether to boost *Raging Bull*. The upcoming v1.1.5 release includes the fixes made by the `@smogon/calc` team, [one of which is switching these formes to their updated versions](https://github.com/smogon/damage-calc/commit/41a9003aa0abaa62b8e809a6281217611fd70413#diff-3746e5ca0880b1b37172b2d4614634581c6431f03cd546fcb49ee79adeb91d37).

Thanks again for your report! :)

**Comment by doshidak** [comment]
@MoltenGluten By the way, would love to credit you for your contribution on the README. Do you have a Smogon forums username or Showdown username you'd like to go by? Otherwise, I'll just credit you with your GitHub. (Unless you don't want to be credited, then let me know as well!)

**Comment by MoltenGluten** [comment]
Thanks for the explanations, I've just got into coding myself after years of telling myself to do it and seeing the process you went through was a nice touch. Keep up the good work,
My Smogon Username is LordHelix138 for the contribution
Thanks so much
