### ISSUE TITLE
FEAT: Options for SET default behavior

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#146]
I often find myself switching to Showdown Usage while playing randoms on Gen 3 OU ladder, where it would be nice to be able to have it default to Showdown Usage instead of the first set from Smogon.

Perhaps a dropdown or setting for which behavior the user wants would be useful.
If that's too crowded, then a simple toggle for defaulting to Showdown Usage would be great.

This comes up frequently when calcing damage against a Skarmory, as almost all players are running Defensive stats, not Offensive stats.

**Comment by doshidak** [comment]
Haha for a sec there, I was like huh wat, you're playing *Randoms* (as in the format, not random people) in OU ?!

Actually funny enough, there's a setting for exactly what you're talking about called *Apply Usage Sets First* in the Calcdex section:

![showdex-hellodex-settings-pane-prioritize-usage-stats](https://github.com/doshidak/showdex/assets/18254287/3eed2bb0-873b-4dcb-8c74-5cccd0e6008d)

We found in the past when rolling out the version with usage stats that the majority of people preferred Smogon stats with the usage info in the dropdowns, instead of the *Showdown Usage* set, hence why it's default off (as shown in the screenshot above). Figured nobody else would care, but I personally wanted it to default to the usage set, so I made it into a setting then (glad I did tho)!

Let me know if that does the trick! c:

**Comment by jmynes** [comment]
How do you access these settings? I can't find the panel

**Comment by doshidak** [comment]
> ~How do you access these settings? I can't find the panel~

The timing HAHA

![image](https://github.com/doshidak/showdex/assets/18254287/8823af67-9955-4d0a-93fe-7870725bc3b7)

Showdex doesn't behave like your traditional browser extension when you click on the Showdex icon next to all your other extensions, which would normally bring up a popup, take you to some page, etc. (Currently does nothing.) Definitely aware of that (& caused some confusion for some users who didn't even know if it was installed/working properly, but that's totally fair & don't blame them), so adding a lil menu for that is in the pipeline, just real low in the priority queue cause the calc is our number one priority hahah.

> Aha, I have to have Hellodex open, which I can't seem to reopen once closed, unless I refresh

Oh ya, that's also something we have planned in the pipeline as well (being able to reopen the Hellodex & even not have it auto-open when Showdown starts). For now tho, you do gotta refresh :c

Sorry about that!

**Comment by jmynes** [comment]
Great, then it sounds like this issue is resolved!
Thanks much
