### ISSUE TITLE
BUG: Ivy Cudgel is always set to Grass type

### ISSUE THREAD

**Issue by alexakreizinger** [doshidak/showdex#156]
(Google Chrome, randbats, using Showdex v1.1.6)

Ivy Cudgel's type doesn't update to reflect different Ogerpon forms—for example, this one should've been Fire, not Grass:

![ogerpon](https://github.com/doshidak/showdex/assets/101227699/ff35f172-bca2-473d-99cf-3952414d10ef)

**Comment by doshidak** [comment]
Hiya!

Aware of this one — it's cause the underlying damage calculator doesn't have the new DLC content yet. We'll be pushing an update with this soon!

In the meantime, you'll have to enable the *Edit Moves* setting in order to manually set *Ivy Cudgel*'s type:

![hellodex-calcdex-show-move-editor](https://github.com/doshidak/showdex/assets/18254287/01a733bf-6163-40c7-b7df-53a5e23d1561)

You can find this under *Advanced* in the Calcdex section of the Hellodex settings. Once set to *Always*, you'll see an "EDIT" button next to the "TERA" button in the Moves table.

Sorry about the inconvenience! :o
