### ISSUE TITLE
showdex is not showing sets

### ISSUE THREAD

**Issue by brunnohalves** [doshidak/showdex#164]
since yesterday, in any battle the sets is not loading. 
of my opponent and mine. not even my sets that are in my teambuilding. I have to set manually any set. 
the settings are corretly, I didnt change anything.
![image](https://github.com/doshidak/showdex/assets/148660483/2fe65e1b-313d-4651-8655-a71ecce3ee93)
can anyone help me?

**Comment by brunnohalves** [comment]
![image](https://github.com/doshidak/showdex/assets/148660483/fe990f11-b328-49fc-bfba-af885c96a629)
is showing this mistake in chrome extension

%cFUCK%c@showdex/redux/store/calcdexSlice %cat update (chrome-extension://dabpnahpcemkfbgfbmegmncjllieilai/main.js:2:1782697) margin-left: 5px;padding: 5px 10px;font-size: 10px;color: #D32F2F;background-color: rgba(255, 255, 255, 0.015);border-top-left-radius: 3px;border-bottom-left-radius: 3px; padding: 5px 10px 5px 0;font-size: 10px;color: #9E9E9E;background-color: rgba(255, 255, 255, 0.015); padding: 5px 10px;font-size: 10px;color: #9E9E9E; Could not find a CalcdexBattleState with battleId battle-gen9randombattle-1973107267-2c4mguuk3ub65910adbwqjm733ctvv6pw

**Comment by doshidak** [comment]
yikes, can you try going into the Hellodex Settings & under the *Cache Sets for* option, set it to **Never**, then back to whatever it was before, like **1 Week** (default)? after doing so, refresh Showdown & see if the sets come back.

as for the error itself, it appears that it was from another game since the battle ID says `gen9randombattle` & your screenshot is `gen8ou`. not entirely sure where that error's from, but could be from an old expired battle.

**Comment by doshidak** [comment]
we did discover an issue with the sets in v1.1.7, which has been addressed in the upcoming v1.1.8 release.

I'll close this PR for now, but feel free to re-open this if you're still having issues after installing the new version.

thanks!
