### ISSUE TITLE
Default Settings button fails

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#166]
I think this button is probably supposed to _set_ defaults, not export them to clipboard?
Either way, it does neither currently:
![image](https://github.com/doshidak/showdex/assets/15176546/0a497adc-73aa-4b7b-b79f-fed13d80947f)

Tested in chrome

**Comment by doshidak** [comment]
I originally intended to export it to your clipboard so that you don't accidentally reset all your settings when trying to close out of it (though not intuitive from the button label, but assumed you'd figure it out).

funny thing is that there is an undo function built-in when you import (you get like 5 seconds I think), so I guess I could do the same for the defaults.

but thanks for letting me know!

**Comment by jmynes** [comment]
I see, makes sense as-is then, as long as it's fixed to work again 😅
