### ISSUE TITLE
FEAT: Add option to auto select mega evolution in nat dex battles

### ISSUE THREAD

**Issue by Fubs** [doshidak/showdex#169]
Currently, you need to manually change the form of a pokemon to see the damage values it would deal/receive after mega evolving. I think it would be useful to automatically do that. 

Some considerations:

- Nat dex formats allow only one mega per team, so if opponent already revealed their mega evolution, then probably don't want to auto select the mega evolution for any of their other pokemon.
- Probably don't want to auto select the mega evolution for pokemon that are switched out. If they switch in, they will still take damage based on the non-mega def/spd stats.
- For the pokemon with two mega forms, it would probably just be easiest to auto select one based on alphabetical order. Or the option could just not auto select the mega form for such pokemon.
- Also probably don't want to auto select the g-max forms in formats where g-max is not legal.

**Comment by doshidak** [comment]
hey Fubs!

actually, the calc *should* be syncing the Mega forme changes for you, but due to a bug introduced in v1.1.7 that re-applies the set once the forme changes, a set with a non-Mega forme (since Megas typically don't have their own unique sets) will reapply the base forme again.

also gave your suggestion a little think, but auto-switching to Mega formes might be a little too complicated to implement for this upcoming version (as you've pointed out, there are quite a bit of nuances that we must consider!).

for now, see if the current fix works for you (once it drops). I'll close this issue when I merge the PR for the upcoming version, but feel free to re-open this or create another one if you still feel the need.

thanks!
