### ISSUE TITLE
Pokemon moves not correct

### ISSUE THREAD

**Issue by skrrtpow** [doshidak/showdex#171]
Enemies moves are wrong like half the time

**Comment by doshidak** [comment]
hi there! specifically for which format?

the moves aren't supposed to be 100% accurate all the time (otherwise, that'd be borderline cheating!). we provide multiple sets for you to choose from, but you yourself must discern which set the Pokémon could possibly be (e.g., that did too much damage, so it's probably the *Choice Band* set, not the *Leftovers* set it currently has).

(side note: a highly requested feature was for us to reverse damage calculate from the actual damages to find the closest matching set, but this is something we're now pretty vocal about **not** doing cause we believe it undermines the competitive integrity of the game.)

but if you're talking about the calc not filling in the revealed moves as they come, then that's an entirely separate issue, i.e., a bug.

regardless, could you clarify a bit more about what you mean here? thanks!

**Comment by skrrtpow** [comment]
oh ok my bad, i thought it was a bug.

**Comment by doshidak** [comment]
no worries! thanks for reporting back c:
