### ISSUE TITLE
Auto update opponents set.

### ISSUE THREAD

**Issue by zuils** [doshidak/showdex#19]
Not really a bug, but could be a huge QoL feature. Here's link of [original comment](https://www.reddit.com/r/stunfisk/comments/xdpbkr/showdex_an_autoupdating_damage_calculator_built/ioco641/?utm_source=share&utm_medium=ios_app&utm_name=iossmf&context=3).

**Comment by doshidak** [comment]
Thanks for your suggestion!

Actually considered adding this as a feature during development cause I realized this was very doable with the information I have available in the Calcdex, but decided against it for the [reasons brought up by camdawgboi](https://www.smogon.com/forums/threads/showdex-an-auto-updating-damage-calculator-built-into-showdown.3707265/post-9335186).

What he mentioned is basically our design philosophy with this extension: we wanted this to be a "helpful timesaver" by automating the tedium of inputting everything into the original Damage Calculator. We had to draw the line somewhere so that it doesn't give those using our extension an "unfair advantage." We still want you to rely on your game sense and draw those inferences yourself (like whether the Pokémon is *Choice-Band*ed based on the actual damage).

However, we do have a similar feature in the pipeline, which will auto-select available sets based on the Pokémon's revealed item and/or ability. Difference here is that we're not cross-checking the set with the actual reported damages—that's something you should be figuring out for yourself!

Hope you can understand!

**Comment by zuils** [comment]
"However, we do have a similar feature in the pipeline, which will auto-select available sets based on the Pokémon's revealed item and/or ability." I should've read the original comment more carefully lol. This is pretty much what the qol feature I was talking about.
