### ISSUE TITLE
BUG: Calcdex lost track of battle against same player in two separate matches

### ISSUE THREAD

**Issue by jmynes** [doshidak/showdex#192]
Once the opponent's Suicune came into play, it did not show up on the sidebar, and my Aerodactyl stopped tracking health/berry status:
![image](https://github.com/doshidak/showdex/assets/15176546/633efe2d-58ca-4a23-b4e0-bd11753c6903)

A refresh did not fix the issue, it made it worse:
![image](https://github.com/doshidak/showdex/assets/15176546/982cbc1e-f4e9-462c-89f7-9b54aa313de8)

Queueing up a new match did fix it, in new matches

**Device:** Desktop computer
**OS & Version:** Windows 10, fully up to date
**Browser:** Microsoft Edge (chromium)
**Showdex Version:** v1.2.3
**Format, if applicable:** ADV OU
**Unfortunately, I forgot to to grab the replay**

**Comment by jmynes** [comment]
I managed to have another matchup with the same player, and it broke my Calcdex tracking again, after only a few turns:
https://replay.pokemonshowdown.com/gen3ou-2060356715-7qkz66xfmzkztx8xhvj4i0vxymmt2dypw
![image](https://github.com/doshidak/showdex/assets/15176546/6e04502c-9fc1-4721-a419-f88534e11466)

**Comment by jmynes** [comment]
First time it's happened to me with a different player

https://replay.pokemonshowdown.com/gen3ou-2066916249
![image](https://github.com/doshidak/showdex/assets/15176546/f85c54bc-a3f5-45b2-a8ac-e6efece63ff1)

**Comment by doshidak** [comment]
LMAO so it turns out that I forgot to sanitize one of the inputs (oopsies), so these Pokémon nicknames ending with `"???"` (like the "Dog???" *Suicune* LOL) & such were forming invalid `RegExp`'s, resulting in the following *silent* initialization crash outside of the UI:

```
Invalid regular expression: /(p2)[a-z]?:\s*(Dog???[\w\s-]*)/i: Nothing to repeat
```

Funny thing too is that this `RegExp` is to parse Showdown's battle log, which includes nicknames, so technically doesn't matter whether you have *Pokémon Nicknames* disabled in the *Show / Hide* settings, e.g.,

```
|switch|p2a: Dog???|Suicune|100/100|[from] Baton Pass
```

Anyway, thanks for letting the dogs out, as well as providing the super detailed report!!

![calcdex-bork-bork](https://github.com/user-attachments/assets/af605311-4f22-44d1-ad1c-6139d2a94555)
