### ISSUE TITLE
Inconsistency with showdown calc on speed

### ISSUE THREAD

**Issue by nishtahir** [doshidak/showdex#210]
Not sure if this is a legit bug or not but I noticed an inconsistency with Ribombee's speed in Calcdex vs the Showdown damage calculator. There's a 1 point difference in the speed stat

<img width="463" alt="Screenshot 2024-07-28 at 12 58 30 AM" src="https://github.com/user-attachments/assets/6c33d179-970e-4c4b-918a-4c2c2f5e6334">

<img width="529" alt="Screenshot 2024-07-28 at 12 58 44 AM" src="https://github.com/user-attachments/assets/e3ac9081-6d84-4c1a-bd46-09d80f4b6461">

I'm not sure what the cause of it is but I figured I'd report it just in case.

Replay in case it's helpful:
https://replay.pokemonshowdown.com/gen9unratedrandombattle-2168759062-ifvjc9ma6k1wq0z49ua3bu9zlt0fn0gpw

**Comment by doshidak** [comment]
hey nice find! turns out it's actually a bug on our end with how we're calculating the SPE stat. I've updated the math to make sure it properly calculates it like the [Damage Calculator](https://github.com/smogon/damage-calc/tree/master/calc).

![calcdex-ribombee-pokestats](https://github.com/user-attachments/assets/6ed1eb8f-2245-403d-a226-afbeea7df06a)

will be made available in this upcoming version, dropping soon. thanks for the detailed report! c:
