### ISSUE TITLE
Hidden Power Damage Wrong

### ISSUE THREAD

**Issue by Shock3600** [doshidak/showdex#45]
Not sure the exact scenario that causes this, but hidden power is often calculated incorrectly. An example is hidden power bug on hariyama saying it will OHKO max defensive celebi when this is in fact not the case. (Chrome)
![image](https://user-images.githubusercontent.com/65835102/193379644-c80b9424-ff9e-47a0-8e99-17d2e7dd3785.png)

**Comment by doshidak** [comment]
Yikes, that's not good :o

Thanks for the bug report, I'll look into this!

**Comment by Shock3600** [comment]
Its actually much worse than that. Its not just hidden power. I had a calc for max attack adamnt cb ttar eq on my starmie, showing it doing like 10% less than the actual damage. Don't have a picture unfortunately

**Comment by Shock3600** [comment]
![image](https://user-images.githubusercontent.com/65835102/193384353-d5a60b1c-c50f-4a3c-8ae3-6b37e96839ef.png)
Here's an example of it happening with max special attack zapdos and thunder

**Comment by doshidak** [comment]
Hey, so I tried to reproduce this issue on my end by first calculating your matchup on the official [calc.ps](https://calc.pokemonshowdown.com). (That way, I can see if it's an issue on my end or the calculator itself.) From your first screenshot, I can see that you must be in gen 3, 4 or 5 since Aurora Veil and Terrain are disabled.

I was able to reproduce the exact damage outputs in gen 3:

![calc-ps-hariyama-hp-bug](https://user-images.githubusercontent.com/18254287/193660206-3cae35f7-70f5-4497-9cf3-c51db19d45ca.png)

Since I was able to reproduce the same *HP Bug* damage range on calc.ps, it appears to be an issue with the calculator itself. (Showdex uses the [same code for damage calculations](https://github.com/smogon/damage-calc/tree/master/calc) as calc.ps, so any bugs with calc.ps will also be present in Showdex.)

Seems to be an [ongoing issue with calc.ps](https://github.com/smogon/damage-calc/issues/336), where *Hidden Power*'s BP doesn't change based on the DVs/IVs. The above damage for *HP Bug* was based on 70 BP, which is the default BP when you select it from the dropdown. Showdex currently doesn't recalculate *Hidden Power*'s BP.

---

Just to double-check, based on [Bulbapedia's entry for *Hidden Power* calculations in gen 3](https://bulbapedia.bulbagarden.net/wiki/Hidden_Power_(move)/Calculation#Generation_III_onward), we can calculate the actual BP of *HP Bug* with the formula:

```
HP_power = floor(
  ((
    HP_lsb2
      + (2 * ATK_lsb2)
      + (4 * DEF_lsb2)
      + (8 * SPE_lsb2)
      + (16 * SPA_lsb2)
      + (32 * SPD_lsb2)
  ) * 40) / 63
) + 30
```

* where `*_lsb2` is the 2nd least significant bit (LSB) of the specified stat's IV.

For *Hariyama*, since it has 31 IVs across the board, the 2nd LSB can be derived as follows:

```
( 31 )_10 = ( 0001 1111 )_2
                     ^ 2nd LSB = 1
```

Then plugging `1` for each `*_lsb2` in the aforementioned formula:

```
HP_power
= floor(
  ((
    1
      + (2 * 1)
      + (4 * 1)
      + (8 * 1)
      + (16 * 1)
      + (32 * 1)
  ) * 40) / 63
) + 30
= floor(((1 + 2 + 4 + 8 + 16 + 32) * 40) / 63) + 30
= floor((63 * 40) / 63) + 30
= floor(40) + 30
= 40 + 30
= 70
```

---

I suppose in the case for *Hariyama*, 70 BP for *HP Bug* would be correct based on its 31 IVs for gen 3, but I can see this being an issue for Pokémon w/ not all 31 IVs, since the resulting BP wouldn't be 70.

Luckily, I can override the BP of any move (as you can do on calc.ps as well), so I'll translate all of this nerdy math into code to make sure *Hidden Power* moves have the correct BP for gens < 4 (since in gens 4+, all *Hidden Power* moves have 60 BP).

As for *HP Bug*'s OHKO, you have critical damages enabled, which results in the range 112.6-132.6%. Otherwise, it would've been 56.1-66.3% against a 252 HP / 252+ DEF *Celebi*, which is a 2HKO. (But at *Celebi*'s current HP of 55%, the calculator would report a guaranteed OHKO.)

Finally, for the 10% less damage on the *EQ*, do you know for sure that your opponent's *Tyranitar* had 252 ATK? Since the calc doesn't know the exact set your opponent is running (e.g., they could've had 80 ATK), there could be discrepancies in the calculations compared to the actual damages. But if so, do you remember what gen and format that battle was in? I'd like to reproduce this issue on my end.

Thanks!
