### ISSUE TITLE
Arrow keys to go back to rooms from Showdex home page

### ISSUE THREAD

**Issue by singiamtel** [doshidak/showdex#63]
I tend to move between rooms using right and left arrow keys, would it be possible to go to previous and next roomchats on this keypress?
I can make a pull request for it if you approve it

Awesome extension btw!

**Comment by doshidak** [comment]
Sure! I'll definitely add that in. This project has `hotkeys-js` already installed, so I'll just quickly add a quick thing to restore arrow key navigation.

(I only learned that was a feature when implementing the Battle Overlay mode. Showdown kept focusing the chat input field, which would blur the dropdowns in the Calcdex constantly. Couldn't figure it out for the longest time, but the fix was to disable the chat input while the overlay was open. Did make me wonder if anyone used this tho LOL...)

I'll keep your issue open until I implement this.

Thanks!
