### ISSUE TITLE
Meloetta is bugged

### ISSUE THREAD

**Issue by meloettabug** [doshidak/showdex#65]
If Meloetta is changed into pirouette-Meloetta automatically, through relic song, it will still be psychic-normal instead of fighting-normal. I did confirm this by battling myself. The problem does not happen if you manually change into pirouette form in the calculator. I noticed it and figured I should say something, other than that I think what you've made is really cool and if I had money I'd give you some

**Comment by meloettabug** [comment]
![pic or it didn't happen](https://user-images.githubusercontent.com/116935712/198814739-12bc236a-1620-404a-bdfa-33bae00603af.PNG)

**Comment by doshidak** [comment]
Hey, thanks for letting me know!

Just checked *Meloetta* on Smogon and you're right, the calc should've updated its typing. I'll take a look into this.

Glad you're enjoying the calc! No need to feel obligated to send us anything—your enjoyment is all we care about, really! Though I appreciate the thought :)

Also, would love to credit you for reporting this bug, but my hunch tells me your GitHub might be made specially for this bug LOL. If you'd like to be credited, let me know what your username is on Smogon Forums!

I'll keep your issue open until this bug is resolved.

**Comment by meloettabug** [comment]
@doshidak yeah I noticed the bug at like 2 a.m. I found the password requirements for making a GitHub account to be quite ridiculous, which for some reason further motivated me to report the bug. You can credit me as IHatePasswords if you feel the need.
