### ISSUE TITLE
Judgement becomes Max Strike upon dynamaxing, changing it to a normal type move in the calculator.

### ISSUE THREAD

**Issue by madamadam-c** [doshidak/showdex#67]
For example, this would mean that it would say that Arceus-Water's Judgement would deal 0% to a Ghost Type and that Dynamaxed Judgement deals less than non-dynamaxed Judgement

![image](https://user-images.githubusercontent.com/17513216/200110331-77d66cb2-08d8-4c29-b905-3a9baa7bcfce.png)
vs
![image](https://user-images.githubusercontent.com/17513216/200110338-fbebf8d3-721f-42de-8e38-93437a6823d2.png)
(in the second image Arceus has been dynamaxed)
![image](https://user-images.githubusercontent.com/17513216/200110351-382261bf-e706-4db5-800f-5d4f26e0454a.png)
same thing with rain boosts
![image](https://user-images.githubusercontent.com/17513216/200110355-939c9cb8-94d7-4dcc-a58b-3d263719504b.png)
![image](https://user-images.githubusercontent.com/17513216/200110393-4e7c7177-935b-4822-a181-56e335bd9a21.png)
non-dmax vs ghost type
![image](https://user-images.githubusercontent.com/17513216/200110404-47bbabe1-95c4-44c8-b26c-b8198ee580a9.png)
dmax vs ghost type

Other than this I have really enjoyed this extension

**Comment by doshidak** [comment]
This is known issue (#55) with the damage calculator itself as we use the same under-the-hood logic as the [O.G Damage Calculator](https://calc.pokemonshowdown.com). If you select *Dynamax* in the O.G Damage Calculator for *Arceus-Water*, you'll see that *Judgment* becomes *Max Strike* (and against a, say, *Gengar*, *Judgment* correctly becomes Water type, but *Max Strike* reports 0 damage since it's still Normal type).

While a fix to directly address this is planned, it'll take awhile since *Judgment* isn't the only move that this bug affects (e.g., this also happens for *Techno Blast* on a *Genesect* with a *Douse Drive*, where the move also becomes *Max Strike* when Dynamaxed). 

(Actually, I'm waiting on what the Showdown/Smogon Dev Team does with Gen 9 first before implementing a fix since I'm assuming a format like Gen 9 National Dex AG will allow Z, Max, and Terastalization, so this bug may potentially be present in Terastalized Max moves.)

In the meantime, we're adding editing features for moves in the upcoming version (releasing soon), so you should be able to correctly set the typing of *Judgment* so that the correctly-typed Max move will appear. A bit annoying, I know, but at least there will be some workaround until we address all the affected moves.

Thanks for your kind words! Happy to hear that :)

I'll keep your issue open until all the affected moves are addressed (just for tracking purposes).
