### ISSUE TITLE
Calcdex failed!

### ISSUE THREAD

**Issue by david-simoes-93** [doshidak/showdex#89]
![image](https://user-images.githubusercontent.com/9117323/208384662-32a5a85d-04dd-41e8-b258-306030aeb4ba.png)

**Comment by doshidak** [comment]
Hiya!

Looked at the error dump in the QR code and it appears that you're on **v1.0.6**, which doesn't have support for Gen 9, thus resulting in the error:

```
Error: Invalid generation 9
```

Showdex is now on [**v1.1.0**](https://github.com/doshidak/showdex/releases/tag/v1.1.0) with proper support for Gen 9.

While updates are normally seamless, the latest version has updated website access permissions (I allowed Showdex to load into [any psim.us server](https://pokemonshowdown.com/servers), as opposed to select servers in prior versions), so you'll need to *manually* update and enable Showdex again in your browser's extensions page. (Future updates should be seamless since I don't imagine updating the extension's permissions again any time soon.)

Alternatively, you can just reinstall the extension if your browser is giving you a hard time updating.

I'll go ahead and close your issue in the meantime. Feel free to open another one if you're still experiencing issues in Gen 9 after updating to v1.1.0.
