### ISSUE TITLE
No Dynamax Option in VGC2022

### ISSUE THREAD

**Issue by ShivaD173** [doshidak/showdex#92]
There is no way to check dynamax calcuations for VGC2022 (and VGC2021 and 2020). It correctly makes calculations when a pokemon is already maxed.

**Comment by doshidak** [comment]
Hi there! While we do hide the *Max* toggle for VGC2023 (since it's Gen 9), other VGCs should be left untouched since they're Gen 8 (e.g., `gen8vgc2022`).

I spectated a VGC2022 game and was able to toggle the Pokémon's Dynamax state no problem (see screenshot below).

<img alt="calcdex-gen8vgc2022-max-toggle" width="386px" src="https://user-images.githubusercontent.com/18254287/208996171-30c4ce6c-382d-4cce-8320-493473044b69.png" />

If you don't have a *Max* toggle like in the screenshot above, please post a screenshot of what it looks like on your end.

Thanks!
