### ISSUE TITLE
Snow (the weather) doesn't affect damage targeting physical defense

### ISSUE THREAD

**Issue by mnittsch** [doshidak/showdex#98]
Browser: Chrome
Showdex version v1.1.1
Setting the weather to snow shows the correct increase in physical defense for ice type pokemon but does not reduce the calculated damage taken. 
Without snow:
![Snow1](https://user-images.githubusercontent.com/9419552/210236843-af3dedea-8bdf-4bc7-9c28-ec2dc7adf50a.png)
With snow:
![Snow2](https://user-images.githubusercontent.com/9419552/210236857-55fae4bf-e5a0-450f-8f40-54a2c53c73e0.png)

**Comment by doshidak** [comment]
Hey there! Thanks for your bug report! :)

Ah, when I had updated the underlying damage calculator (same one as [calc.ps](https://calc.pokemonshowdown.com)) for v1.1.1, apparently [they had added `'Snow'` as a weather condition](https://github.com/smogon/damage-calc/blob/5ada271721cab5218dbbd7acf13b0b236eafbbc7/calc/src/data/interface.ts#L18-L19), which I didn't notice :(

Before, [calc.ps](https://calc.pokemonshowdown.com) had used `'Hail'` in lieu of `'Snow'` (as a quick fix to push out Gen 9 support ASAP, I'm assuming), but now that they've added proper support for it, Showdex isn't correctly reporting the weather now.

(While we display *Snow*, it's actually reported as `'Hail'` under-the-hood to the calculator since `'Snow'` didn't exist before, as previously mentioned.)

Nice find! I'll include a fix in the next patch.

**Comment by doshidak** [comment]
Also would love to credit you for your contribution in the README, so if you want, let me know what your Smogon forums username is; otherwise, I'll just link your GitHub! (...unless you explicitly don't want to be credited.)

Thanks again :)

**Comment by mnittsch** [comment]
Linking the GitHub is fine! 
Thanks for your work on this addon :)
